CREATE TABLE group_request (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, target_user_id INTEGER NOT NULL, target_group_id INTEGER NOT NULL, status INTEGER DEFAULT NULL, CONSTRAINT FK_BD97DB936C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BD97DB9324FF092E FOREIGN KEY (target_group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_BD97DB936C066AFE ON group_request (target_user_id);
CREATE INDEX IDX_BD97DB9324FF092E ON group_request (target_group_id);
CREATE TABLE "user" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles CLOB NOT NULL --(DC2Type:json)
, nickname VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email);
CREATE TABLE message (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, owner_id INTEGER DEFAULT NULL, thread_id INTEGER NOT NULL, content CLOB NOT NULL, has_been_edited BOOLEAN NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, modified_at DATETIME DEFAULT NULL, CONSTRAINT FK_B6BD307F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B6BD307FE2904019 FOREIGN KEY (thread_id) REFERENCES thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_B6BD307F7E3C61F9 ON message (owner_id);
CREATE INDEX IDX_B6BD307FE2904019 ON message (thread_id);
CREATE TABLE thread (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, owner_id INTEGER NOT NULL, related_group_id INTEGER DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content CLOB NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, CONSTRAINT FK_31204C837E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_31204C8358D797EA FOREIGN KEY (related_group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_31204C837E3C61F9 ON thread (owner_id);
CREATE INDEX IDX_31204C8358D797EA ON thread (related_group_id);
CREATE TABLE "group" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, owner_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, CONSTRAINT FK_6DC044C57E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_6DC044C57E3C61F9 ON "group" (owner_id);
CREATE TABLE group_user (group_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(group_id, user_id), CONSTRAINT FK_A4C98D39FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A4C98D39A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_A4C98D39FE54D947 ON group_user (group_id);
CREATE INDEX IDX_A4C98D39A76ED395 ON group_user (user_id);